all: ejercicios.pdf
	pdflatex -shell-escape -interaction=nonstopmode -file-line-error beamergreedy.tex
	pdflatex -shell-escape -interaction=nonstopmode -file-line-error beamergreedy.tex
	pdflatex -shell-escape -interaction=nonstopmode -file-line-error memoriagreedy.tex
	pdflatex -shell-escape -interaction=nonstopmode -file-line-error memoriagreedy.tex
	# g++ -std=c++11 ./Viajante/grafo.cpp
	./.limpieza.sh
