#!/bin/bash
	pdflatex -shell-escape -interaction=nonstopmode -file-line-error ./beamergreedy.tex
	pdflatex -shell-escape -interaction=nonstopmode -file-line-error ./beamergreedy.tex
	pdflatex -shell-escape -interaction=nonstopmode -file-line-error ./memoriagreedy.tex
	pdflatex -shell-escape -interaction=nonstopmode -file-line-error ./memoriagreedy.tex
	echo "Limpieza"
	find . -regex ".*~" -exec rm -r {} \;

	rm -f ./*.aux
	rm -f ./*.log
	rm -f ./*.nav
	rm -f ./*.out
	rm -f ./*.vrb
	rm -f ./*.snm
	rm -f ./*.toc
	rm -f ./*.gz
